# -*- coding: utf-8 -*-
"""heartbeattrial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SQTs3NqdDm1JT0qvXUU0ytARMSutrR69
"""

import librosa
import numpy as np
import matplotlib.pyplot as plt

# -----------------------------
# LOAD AUDIO
# -----------------------------
audio_path = "heartbeat.wav"  # EDIT
signal, fs = librosa.load(audio_path, sr=None)

time = np.arange(len(signal)) / fs

# -----------------------------
# FILTER (20–150 Hz)
# -----------------------------
from scipy.signal import butter, filtfilt

def bandpass(data, low, high, fs, order=3):
    nyq = 0.5 * fs
    b, a = butter(order, [low/nyq, high/nyq], btype='band')
    return filtfilt(b, a, data)

filtered = bandpass(signal, 20, 150, fs)

# -----------------------------
# ZERO CROSSING DETECTION
# -----------------------------
zero_crossings = np.where(np.diff(np.sign(filtered)) > 0)[0]
beat_times = zero_crossings / fs

# -----------------------------
# PLOTS
# -----------------------------
plt.figure()
plt.plot(time, filtered)
plt.plot(beat_times, filtered[zero_crossings], 'rx')
plt.xlabel("Time (s)")
plt.ylabel("Amplitude")
plt.title("Heartbeat Detection using Zero Crossing")
plt.show()

# -----------------------------
# CALCULATIONS
# -----------------------------
total_beats = len(beat_times)
duration_min = time[-1] / 60
bpm = total_beats / duration_min

print("Total Beats:", total_beats)
print("Beats per minute:", bpm)

# Beats per 10 seconds
beats_10s = []
for t in np.arange(0, time[-1], 10):
    beats_10s.append(np.sum((beat_times >= t) & (beat_times < t+10)))

print("Beats per 10 seconds:", beats_10s)
